Repository DanishAbdullahPy/DanishAbdullahPy.github.io, pull requests merged in 2022-10, with the labels that each got.

#1 Create lmao
  lmao
Labels: hacktoberfest-accepted

#2 Update lmao
  lmao
Labels: hacktoberfest-accepted, hacktober-fest, hacktoberfest-2022

#3 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktober-fest, hacktoberfest-2022

#4 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest-2022
